version: "3.8"

services:
  postgres:
    image: supabase/postgres
    container_name: supabase_postgres
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - ./data:/var/lib/postgresql/data

  gotrue:
    image: supabase/gotrue:v2.132.0
    container_name: supabase_gotrue
    depends_on:
      - postgres
    environment:
      GOTRUE_SITE_URL: ${GOTRUE_SITE_URL}
      GOTRUE_JWT_SECRET: ${GOTRUE_JWT_SECRET}
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    ports:
      - "9999:9999"
    restart: unless-stopped

  studio:
    image: supabase/studio:latest
    container_name: supabase_studio
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${GOTRUE_JWT_SECRET}
    ports:
      - "3001:3000"
    restart: unless-stopped
