version: "3.8"

services:
  db:
    image: supabase/postgres:15.8.1.116
    container_name: supabase_db
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - supabase_net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 10

  auth:
    image: supabase/gotrue:v2.177.0
    container_name: supabase_auth
    entrypoint: ["/bin/bash", "-c", "/app/init-auth.sh && /app/start.sh"]
    restart: unless-stopped
    volumes:
      - ./scripts/init-auth.sh:/app/init-auth.sh
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      GOTRUE_API_HOST: "0.0.0.0"
      GOTRUE_API_PORT: "9999"
      API_EXTERNAL_URL: ${API_EXTERNAL_URL}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/postgres
      GOTRUE_SITE_URL: ${API_EXTERNAL_URL}
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9999/health"]
      interval: 5s
      retries: 3
    networks:
      - supabase_net

  rest:
    image: postgrest/postgrest:v12.0.1
    container_name: supabase_rest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGRST_DB_URI: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"
    networks:
      - supabase_net

  realtime:
    image: supabase/realtime:v2.33.4
    container_name: supabase_realtime
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      RLIMIT_NOFILE: 1048576
    ports:
      - "4000:4000"
    networks:
      - supabase_net

  storage:
    image: supabase/storage-api:v1.25.7
    container_name: supabase_storage
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      auth:
        condition: service_healthy
    environment:
      ANON_KEY: ${ANON_KEY}
      SERVICE_KEY: ${SERVICE_ROLE_KEY}
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
      PGRST_JWT_SECRET: ${JWT_SECRET}
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
    volumes:
      - ./storage:/var/lib/storage
    networks:
      - supabase_net

  studio:
    image: supabase/studio:2025.06.30-sha-6f5982d
    container_name: supabase_studio
    restart: unless-stopped
    depends_on:
      auth:
        condition: service_healthy
    ports:
      - "3001:3000"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      STUDIO_PG_META_URL: http://db:8080
      SUPABASE_URL: ${API_EXTERNAL_URL}
      SUPABASE_ANON_KEY: ${ANON_KEY}
      AUTH_JWT_SECRET: ${JWT_SECRET}
    networks:
      - supabase_net

networks:
  supabase_net:
