# Start FROM the same Supabase Auth image
FROM supabase/gotrue:v2.177.0

USER root

# Install bash and PostgreSQL client (for pg_isready)
RUN apk add --no-cache bash postgresql-client

COPY scripts/auth-init.sh /app/auth-init.sh

RUN ls -la /app

# Make sure it's executable
RUN chmod +x /app/auth-init.sh

USER supabase


